### PR TITLE
Update version and mappings for 1.12

### PR DESCRIPTION
**Pull request by Ristovski**

### CODE REVIEW

**Comment by asiekierka** [comment]
Not necessary, the code is Minecraft/Forge agnostic and only relies on the Launchwrapper and some unlikely to change flags set by FML in the Launchwrapper blackboard.

**Comment by Ristovski** [comment]
Well considering you don't have a 1.12 build up on your site, people might try to compile with gradle? I mean sure, what are they even doing if they can't update the versions themselves, but I personally see no harm.

**Comment by asiekierka** [comment]
It was not marked as 1.12-compatible simply because I was not aware of it having been tested. The same build works on Minecraft 1.6+ for as long as the Launchwrapper isn't redesigned (which might happen with Minecraft 1.13, but no guarantees on that).

I see no harm either, but also no real reason to make this change officially unless a future version of Forge adds a feature I'd be interested in using.

**Comment by Ristovski** [comment]
Fair enough :smiley:

**Pull request closed without merging**
